[project]
authors = [
  "Giulio Ermanno Pibiri <jeis90@gmail.com>",
]
channels = [
  "conda-forge"
]
description = "Fulgor is a colored de Bruijn graph index for large-scale matching and color queries, powered by SSHash and GGCAT"
name = "fulgor"
platforms = [
  "linux-64",
  "osx-64",
  "osx-arm64",
]
version = "3.0.0"

[tasks]
clean = "rm -rf build/"
ci = { depends-on = ["submodules", "configure", "build"] }
build = { cmd = "make -j", cwd = "build", depends-on = ["submodules", "configure"] }
configure = { cmd = "mkdir -p build && cd build && cmake ..",  depends-on = ["submodules"] }
submodules = "git submodule update --init --recursive"

[dependencies]
cxx-compiler = ">=1.8.0,<2"
cmake = ">=3.31.1,<4"
rust = ">=1.82.0,<1.83"
make = ">=4.4.1,<5"
zlib = ">=1.3.1,<2"
