[project]
authors = ["Luiz Irber <contact+github@luizirber.org>"]
channels = [
#  "conda-forge/label/rust_dev",
  "conda-forge"
]
description = "Add a short description here"
name = "fulgor"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cxx-compiler = ">=1.8.0,<2"
cmake = ">=3.31.1,<4"
ninja = ">=1.12.1,<2"
#rust = "==1.81.0.dev20240720"
rust = ">=1.82.0,<1.83"
make = ">=4.4.1,<5"
zlib = ">=1.3.1,<2"
