name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  default:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.38.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - run: pixi run ci

      - run: "./build/fulgor | grep 'Fulgor: a colored de Bruijn graph index'"
        name: check
